### PR TITLE
Extract the pdb path

### PR DESCRIPTION
**Pull request by nafest**
Normally the path to the PDB file is embedded in the unit tests
executable. Try to extract it and use it if present.

### CODE REVIEW

**Comment by NewProggie** [comment]
Nice, I'd need that in my project. :thumbsup:

**Comment by csoltenborn** [comment]
Looks interesting indeed at first sight - give us a couple of days to review the pull request. It won't take too long...

**Comment by csoltenborn** [comment]
And, btw, thanks for the pull request, @nafest :-)

**Comment by jgefele** [comment]
Hi @nafest,

thanks a lot for your contribution.

There is some code duplication with the `ImportsParser` in [DiaResolver/NativeMethods.cs](https://github.com/csoltenborn/GoogleTestAdapter/blob/master/GoogleTestAdapter/DiaResolver/NativeMethods.cs) which uses native WINAPI methods from `imageHlp.dll` and `dbgHelp.dll` to handle most of the PE parsing. Particularly, your lines 109 to 283 could be turned into just a couple of library calls.

If you're familiar with native calls from C# (or don't fear getting into it) it would be great if you could refactor your code accordingly (and move it into NativeMethods.cs). Otherwise give me a shout and I'll assist or do it myself.

Cheers,
Jonas

**Comment by nafest** [comment]
I guess I can do that.

**Comment by nafest** [comment]
I moved all code to NativeMethods.c. I hoped that the VirtualAddress->Offset conversion would be unnecessaryif I use MapAndLoad, but that turned out to be wrong.

NativeMethods.c now contains a lot of structs from winnt.h. As all structs use an explicit layout, I could drop all fields that are not needed to get the path. What do you think?

**Comment by jgefele** [comment]
Hi @nafest,

thanks a lot for your work. I'm sorry for coming back to you so late and for being so unclear in my last comment. Most of the work could really be done by a call to ImageDirectoryEntryToData and to ImageRvaToVa.

I have merged your pull request and applied the substitution with library calls.

Cheers,
Jonas

**Comment by nafest** [comment]
Just had a look at your changes. That's way simpler than my way, indeed. Thanks for integrating this feature. I'm looking forward to reenable automatic extension updates ;-)

**Comment by csoltenborn** [comment]
Thanks to both of you! We are going to release 0.6 tomorrow night...

**Pull request merged**
