### PR TITLE
Add support for name parameter tests

### PR DESCRIPTION
**Pull request by wasabinza**
I think I have a minimal set that leaves the existing tests cases as is but enables named parameterised tests.
I do realise you will probably wait till after the big merge.

https://github.com/csoltenborn/GoogleTestAdapter/issues/150

### CODE REVIEW

**Comment by csoltenborn** [comment]
Thanks for your pull request! However, this should go against branch `develop`. Note that the CI build triggered by your pull request failed because of some build server hickup - I repeated the build, which then worked fine (despite the failing tests) and is now linked above (the VSIX file is provided under *Artifacts*); not sure whether you've gotten a notification about that second build.

**Comment by wasabinza** [comment]
I have changed my pull request.

**Comment by wasabinza** [comment]
I guess I still have some cases, which are the old format where I'm not correctly differentiating between Parameterized tests and Simple cause now I'm requiring the new format...

GoogleTestAdapter.TestCases.ListTestsParserTests.ParseListTestsOutput_TestWithParamAndTestNameSeparatorOldFormat_CorrectParsing

**Comment by csoltenborn** [comment]
Here are some hints already for fixing some of the tests:

* Since you have added tests to the `SampleTests/Tests` project, you need to adjust  `GoogleTestAdapter.Tests.Common::TestResources::NrOfTests` etc.
* Our end-to-end tests are golden file based. To adjust the golden files in a simple way after changes have made to the test executables,
  1. set `GoogleTestAdapter.Tests.Common::TestMetadata::OverwriteTestResults` to true,
  2. re-run the end-to-end tests,
  3. set it back to false,
  4. and commit the resulting changes to golden files

Note, however, that the outgoing changes of the golden files need to be verified - otherwise, we'd "fix a broken state".

I'll have a closer look at your PR at the weekend...

**Comment by csoltenborn** [comment]
You are exactly right (and victim of support for a pre-1.7.0 version of gtest :-|). Despite that, your patch looks good in general! Here are a couple of remarks:

* It might be an option to explicitly check all conditions of the old format(s) to cope with that problem, and only otherwise perform normally.
* Despite that, GTA relies on the ids per testcase being distinct. Thus, I guess some logic is needed to catch cases where the user has messed up the functor with respect to this - these cases should probably 
be ignored with a warning.
* Please add tests checking different formats of custom values both for test id and test param, and also a test checking whether the "non-distinct functor" check indeed works as expected.
* Adjusting the numbers in `TestResources` fixes some of the existing tests, the other ones should be fixed by the above and updating the according golden files. One test checks the number of test cases found in the gtest 1.7.0 version of `Tests.exe` - I suggest to add a constant `NrOfGtest170CompatibleTests` to `TestResources` and an optional parameter `expectedNrOfTestCases` to `GoogleTestDiscovererTests::FindTests`.
* Finally, we should probably update the documentation with respect to the supported functionality and the restrictions to the values the functors might be produce (`\w`). Feel free to do this if you want to - otherwise, I can update it myself...

Let me know if you need any more assistance - looking forward to your updated pull request!

**Comment by csoltenborn** [comment]
FYI: I do not consider this a bug since it appears to be a new feature of gtest 1.8.0 (and have thus renamed issue and pull request)...

**Comment by csoltenborn** [comment]
Since you haven't come back so far, I hope that I have not overestimated the amount of time you are willing or able to spend on this - let me know if I'm asking too much ;-)

**Comment by wasabinza** [comment]
Sorry I will try and get back to it, I have moved on to other tasks
recently.
Shane

**Comment by csoltenborn** [comment]
Don't worry, take your time! Just wanted to know whether I was the reason ;-)

**Comment by wasabinza** [comment]
I have added the optional count to findTests and set NrOfGtest170CompatibleTests  for that run.
I don't really know the range of old output formats.  I wondered if I can tell the old output based on the separator character?  maybe :: and then fall back to the old regular expression. This is what I have just committed but that fails the ParseListTestsOutput_TestWithTypeParamAndPrefixOldFormat_CorrectParsing cause that one doesn't set a special separator.  Is it correct to require such a separator?
or another way of asking...
Do the old tests that don't have the # TypeParam or # GetParam text always have a separator other than ""?
Is there a good set of sample outputs we are trying to cope with?  The parser tests seem slightly abstracted by setting the two parameters to the ListTestsParser rather than just putting in text.
I guess I'm hoping you will say that ParseListTestsOutput_TestWithTypeParamAndPrefixOldFormat_CorrectParsing should have a non empty separator set.

**Comment by csoltenborn** [comment]
The separator does not affect matching, but only creation of display names (see description of option *TestNameSeparator*). This thing smoke-tests whether we can still cope with gtest 1.7.0, and additionally checks whether the configured separator is reflected in the display name (which is a test smell - sorry for that ;-) ).

The difference of the old format seems to be that the parameter is not printed (be it a type or value parameter). Thus, we basically check whether the suite or test name has a `/`, but no parameter. It's then old format and either a type or value parameterized test (depending on whether the `/` is in the suite or the test name).

I might have an idea on how to distinguish the cases, but don't have time right now to check the exact output format gtest produces - I will come back to you on this probably tomorrow...

**Comment by wasabinza** [comment]
I'm going to reopen this with my develop branch

**Pull request closed without merging**
